/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AuctionRepository__factory } from "./AuctionRepository__factory";
export { DeedRepository__factory } from "./DeedRepository__factory";
